# Generated by Django 5.1 on 2024-09-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='prizes',
            field=models.ManyToManyField(to='player.prize'),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
