# Generated by Django 5.1 on 2024-09-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_prizes_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
