# Generated by Django 5.1 on 2024-09-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/'),
        ),
    ]
