# Generated by Django 5.1 on 2024-09-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_level_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='avatar',
        ),
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/'),
        ),
    ]
