# Generated by Django 5.1 on 2024-09-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_alter_player_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/'),
        ),
    ]
