# Generated by Django 5.1 on 2024-09-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_alter_levelprize_received_alter_player_prizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='prizes',
        ),
    ]
