# Generated by Django 5.1 on 2024-09-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_remove_player_prizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.AddField(
            model_name='player',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
